/**
 * SHADOW DEFENSE - data.js
 * Definições de Torres, Inimigos, Chefes, Upgrades, Geradores, Árvore de Habilidades e Conquistas
 */

const GAME_DATA = {
  // Configurações Globais
  CONFIG: {
    INITIAL_LIVES: 100,
    INITIAL_COINS: 500,
    COMBO_DECAY_TIME_MS: 3000, // Tempo sem clicar até o combo zerar
    BASE_CRIT_CHANCE: 0.05,    // 5% chance crítica inicial
    BASE_CRIT_MULT: 5.0,       // Multiplicador crítico inicial (5x)
    MAX_LEVEL: 100,
  },

  // Raridades do Jogo
  RARITIES: {
    common: { name: 'Comum', color: '#9ca3af', border: '#4b5563', bg: 'rgba(156,163,175,0.15)', mult: 1.0 },
    uncommon: { name: 'Incomum', color: '#22c55e', border: '#15803d', bg: 'rgba(34,197,94,0.15)', mult: 1.25 },
    rare: { name: 'Rara', color: '#38bdf8', border: '#0284c7', bg: 'rgba(56,189,248,0.15)', mult: 1.6 },
    epic: { name: 'Épica', color: '#c084fc', border: '#9333ea', bg: 'rgba(192,132,252,0.18)', mult: 2.2 },
    legendary: { name: 'Lendária', color: '#facc15', border: '#ca8a04', bg: 'rgba(250,204,21,0.2)', mult: 3.2 },
    mythic: { name: 'Mítica', color: '#f43f5e', border: '#be123c', bg: 'rgba(244,63,94,0.22)', mult: 5.0 },
  },

  // Defesas & Torres
  TOWERS: {
    pistol: {
      id: 'pistol',
      name: 'Pistola Rápida',
      description: 'Dispara projéteis balísticos rápidos em alvos individuais.',
      icon: '🔫',
      rarity: 'common',
      unlockLevel: 1,
      cost: 100,
      damage: 15,
      range: 110,
      attackSpeed: 1.2, // Tiros por segundo
      projectileSpeed: 500,
      type: 'single',
      upgradeCostMult: 1.45,
      damagePerLevel: 6,
      rangePerLevel: 4,
      bulletColor: '#fef08a',
    },
    spikes: {
      id: 'spikes',
      name: 'Armadilha de Espinhos',
      description: 'Espinhos sombrios no chão que ferem inimigos que passam por perto.',
      icon: '⛓️',
      rarity: 'common',
      unlockLevel: 2,
      cost: 180,
      damage: 22,
      range: 85,
      attackSpeed: 1.0,
      projectileSpeed: 0, // Aura/Ground
      type: 'aoe_ground',
      upgradeCostMult: 1.4,
      damagePerLevel: 8,
      rangePerLevel: 3,
      bulletColor: '#94a3b8',
    },
    rifle: {
      id: 'rifle',
      name: 'Rifle de Precisão',
      description: 'Longo alcance e alto impacto perfurante.',
      icon: '🎯',
      rarity: 'uncommon',
      unlockLevel: 3,
      cost: 280,
      damage: 48,
      range: 160,
      attackSpeed: 0.8,
      projectileSpeed: 650,
      type: 'single',
      upgradeCostMult: 1.5,
      damagePerLevel: 18,
      rangePerLevel: 6,
      bulletColor: '#38bdf8',
    },
    campfire: {
      id: 'campfire',
      name: 'Fogueira Mística',
      description: 'Irradia chamas arcanas contínuas queimando criaturas próximas.',
      icon: '🔥',
      rarity: 'uncommon',
      unlockLevel: 4,
      cost: 450,
      damage: 12,
      range: 100,
      attackSpeed: 2.5,
      projectileSpeed: 300,
      type: 'dot_fire',
      upgradeCostMult: 1.45,
      damagePerLevel: 5,
      rangePerLevel: 5,
      bulletColor: '#fb923c',
    },
    electric: {
      id: 'electric',
      name: 'Torre Elétrica',
      description: 'Dispara raios sombrios que saltam entre múltiplos inimigos.',
      icon: '⚡',
      rarity: 'rare',
      unlockLevel: 5,
      cost: 700,
      damage: 42,
      range: 130,
      attackSpeed: 1.1,
      projectileSpeed: 800,
      type: 'chain_lightning',
      chainTargets: 3,
      upgradeCostMult: 1.55,
      damagePerLevel: 16,
      rangePerLevel: 5,
      bulletColor: '#a855f7',
    },
    ice: {
      id: 'ice',
      name: 'Torre de Gelo',
      description: 'Lança orbes congelantes que reduzem a velocidade dos monstros em 40%.',
      icon: '❄️',
      rarity: 'rare',
      unlockLevel: 7,
      cost: 950,
      damage: 28,
      range: 120,
      attackSpeed: 0.9,
      projectileSpeed: 400,
      type: 'slow_ice',
      slowFactor: 0.6, // Reduz para 60%
      slowDuration: 2.5,
      upgradeCostMult: 1.5,
      damagePerLevel: 10,
      rangePerLevel: 5,
      bulletColor: '#67e8f9',
    },
    garlic: {
      id: 'garlic',
      name: 'Dentes de Alho Sagrado',
      description: 'Relíquia purificadora que causa dano massivo amplificado a vampiros e mortos-vivos.',
      icon: '🧄',
      rarity: 'epic',
      unlockLevel: 8,
      cost: 1350,
      damage: 75,
      range: 125,
      attackSpeed: 1.3,
      projectileSpeed: 450,
      type: 'anti_undead',
      upgradeCostMult: 1.58,
      damagePerLevel: 28,
      rangePerLevel: 6,
      bulletColor: '#fef08a',
    },
    cannon: {
      id: 'cannon',
      name: 'Canhão Sombrio',
      description: 'Bombas explosivas com grande área de impacto.',
      icon: '💣',
      rarity: 'epic',
      unlockLevel: 10,
      cost: 1800,
      damage: 130,
      range: 140,
      attackSpeed: 0.55,
      projectileSpeed: 350,
      type: 'splash',
      splashRadius: 55,
      upgradeCostMult: 1.6,
      damagePerLevel: 50,
      rangePerLevel: 5,
      bulletColor: '#ef4444',
    },
    legendary_orb: {
      id: 'legendary_orb',
      name: 'Orbe Lendário do Abismo',
      description: 'Feixe contínuo de aniquilação que desintegra os invasores.',
      icon: '🔮',
      rarity: 'legendary',
      unlockLevel: 15,
      cost: 3800,
      damage: 260,
      range: 175,
      attackSpeed: 1.8,
      projectileSpeed: 900,
      type: 'beam',
      upgradeCostMult: 1.65,
      damagePerLevel: 95,
      rangePerLevel: 8,
      bulletColor: '#eab308',
    },
    mythic_core: {
      id: 'mythic_core',
      name: 'Núcleo do Caos Mítico',
      description: 'Arma definitiva alimentada por matéria escura pura.',
      icon: '🌌',
      rarity: 'mythic',
      unlockLevel: 20,
      cost: 8500,
      damage: 550,
      range: 200,
      attackSpeed: 1.4,
      projectileSpeed: 950,
      type: 'chaos_nova',
      upgradeCostMult: 1.75,
      damagePerLevel: 210,
      rangePerLevel: 10,
      bulletColor: '#f43f5e',
    }
  },

  // Inimigos Comuns
  ENEMIES: {
    zombie: {
      id: 'zombie',
      name: 'Zumbi Decrépito',
      icon: '🧟',
      baseHp: 65,
      speed: 65, // Pixels por segundo
      damage: 1, // Dano à base
      reward: 12,
      xp: 8,
      color: '#4ade80',
      radius: 14,
    },
    skeleton: {
      id: 'skeleton',
      name: 'Esqueleto Ágil',
      icon: '💀',
      baseHp: 48,
      speed: 100,
      damage: 1,
      reward: 15,
      xp: 10,
      color: '#e2e8f0',
      radius: 12,
    },
    vampire: {
      id: 'vampire',
      name: 'Vampiro Noturno',
      icon: '🧛',
      baseHp: 110,
      speed: 85,
      damage: 2,
      reward: 26,
      xp: 16,
      color: '#f43f5e',
      radius: 15,
    },
    ghost: {
      id: 'ghost',
      name: 'Fantasma Esmorecido',
      icon: '👻',
      baseHp: 90,
      speed: 75,
      damage: 2,
      reward: 28,
      xp: 18,
      color: '#a78bfa',
      radius: 14,
      resistance: 'physical',
    },
    werewolf: {
      id: 'werewolf',
      name: 'Lobisomem Voraz',
      icon: '🐺',
      baseHp: 210,
      speed: 95,
      damage: 3,
      reward: 45,
      xp: 30,
      color: '#b45309',
      radius: 18,
    }
  },

  // Chefes Especiais (A cada 10 ondas)
  BOSSES: {
    10: {
      name: 'Rei Zumbi da Peste',
      icon: '👑🧟',
      hpMultiplier: 8.5,
      speed: 48,
      damage: 12,
      reward: 450,
      xp: 220,
      color: '#22c55e',
      radius: 26,
      aura: 'rgba(34, 197, 94, 0.4)',
      title: 'Monarca da Podridão',
    },
    20: {
      name: 'Lorde Vampiro Vladis',
      icon: '👑🧛',
      hpMultiplier: 12.0,
      speed: 68,
      damage: 18,
      reward: 1100,
      xp: 500,
      color: '#e11d48',
      radius: 28,
      aura: 'rgba(225, 29, 72, 0.45)',
      title: 'Soberano de Sangue',
    },
    30: {
      name: 'Rei Esqueleto Imortal',
      icon: '👑💀',
      hpMultiplier: 16.5,
      speed: 55,
      damage: 24,
      reward: 2400,
      xp: 950,
      color: '#cbd5e1',
      radius: 30,
      aura: 'rgba(203, 213, 225, 0.45)',
      title: 'Tirano das Criptas',
    },
    40: {
      name: 'Fantasma Ancestral Supremo',
      icon: '👑👻',
      hpMultiplier: 22.0,
      speed: 62,
      damage: 30,
      reward: 4500,
      xp: 1600,
      color: '#c084fc',
      radius: 32,
      aura: 'rgba(192, 132, 252, 0.5)',
      title: 'Espectro do Vazio',
    },
    50: {
      name: 'Lobisomem Alfa do Crepúsculo',
      icon: '👑🐺',
      hpMultiplier: 30.0,
      speed: 78,
      damage: 40,
      reward: 9000,
      xp: 3000,
      color: '#f59e0b',
      radius: 35,
      aura: 'rgba(245, 158, 11, 0.55)',
      title: 'Predador Primordial',
    },
    generic: {
      name: 'Titã das Sombras Colossal',
      icon: '👑👹',
      hpMultiplier: 38.0,
      speed: 60,
      damage: 50,
      reward: 15000,
      xp: 5000,
      color: '#9333ea',
      radius: 36,
      aura: 'rgba(147, 51, 234, 0.6)',
      title: 'Arauto do Apocalipse',
    }
  },

  // Upgrades de Clique do Cristal Sombrio
  CLICK_UPGRADES: [
    { id: 'click_1', name: 'Toque Aprimorado', addClick: 1, baseCost: 15, costMult: 1.25, icon: '👆', desc: '+1 moeda por clique' },
    { id: 'click_2', name: 'Toque Poderoso', addClick: 5, baseCost: 120, costMult: 1.30, icon: '✨', desc: '+5 moedas por clique' },
    { id: 'click_3', name: 'Toque Arcano', addClick: 10, baseCost: 650, costMult: 1.32, icon: '🔮', desc: '+10 moedas por clique' },
    { id: 'click_4', name: 'Toque Sombrio', addClick: 25, baseCost: 2800, costMult: 1.35, icon: '🌑', desc: '+25 moedas por clique' },
    { id: 'click_5', name: 'Toque Lendário', addClick: 50, baseCost: 12000, costMult: 1.38, icon: '⚡', desc: '+50 moedas por clique' },
    { id: 'click_6', name: 'Toque Mítico', addClick: 100, baseCost: 60000, costMult: 1.42, icon: '👑', desc: '+100 moedas por clique' },
  ],

  // Combos de Cliques e Bônus
  COMBO_TIERS: [
    { count: 10, bonusPercent: 10, name: 'Combo Sombrio' },
    { count: 25, bonusPercent: 25, name: 'Fúria Sombria' },
    { count: 50, bonusPercent: 50, name: 'Êxtase Arcano' },
    { count: 100, bonusPercent: 100, name: 'Tempestade Sombria' },
    { count: 250, bonusPercent: 200, name: 'Domínio do Abismo' },
    { count: 500, bonusPercent: 500, name: 'DEUS DAS SOMBRAS' },
  ],

  // Geradores Automáticos de Moedas (Idle)
  AUTO_GENERATORS: [
    { id: 'gen_1', name: 'Minerador Sombrio', addGps: 1, baseCost: 50, costMult: 1.20, icon: '⛏️', desc: '+1 moeda/segundo' },
    { id: 'gen_2', name: 'Poço Arcano', addGps: 5, baseCost: 320, costMult: 1.22, icon: '⛲', desc: '+5 moedas/segundo' },
    { id: 'gen_3', name: 'Tesouro Encantado', addGps: 15, baseCost: 1400, costMult: 1.24, icon: '🏺', desc: '+15 moedas/segundo' },
    { id: 'gen_4', name: 'Banco Sombrio', addGps: 50, baseCost: 5500, costMult: 1.28, icon: '🏦', desc: '+50 moedas/segundo' },
    { id: 'gen_5', name: 'Portal das Sombras', addGps: 100, baseCost: 22000, costMult: 1.32, icon: '🌀', desc: '+100 moedas/segundo' },
    { id: 'gen_6', name: 'Núcleo Mítico', addGps: 500, baseCost: 110000, costMult: 1.36, icon: '🪐', desc: '+500 moedas/segundo' },
  ],

  // Árvore de Talentos Econômicos (Melhorias Permanentes)
  ECONOMY_TREE: [
    { id: 'tree_click_boost', name: 'Mãos de Midas Sombrio', maxLevel: 10, costBase: 250, costMult: 1.6, icon: '🖐️', desc: '+15% de poder a todos os cliques por nível', effectType: 'click_pct', effectVal: 0.15 },
    { id: 'tree_idle_boost', name: 'Poder Automatizado', maxLevel: 10, costBase: 400, costMult: 1.65, icon: '⚙️', desc: '+15% de rendimento de geradores por nível', effectType: 'idle_pct', effectVal: 0.15 },
    { id: 'tree_crit_chance', name: 'Olho do Destino', maxLevel: 10, costBase: 600, costMult: 1.7, icon: '👁️', desc: '+2% de chance crítica de clique por nível', effectType: 'crit_chance', effectVal: 0.02 },
    { id: 'tree_crit_mult', name: 'Golpe Devastador', maxLevel: 10, costBase: 800, costMult: 1.75, icon: '💥', desc: '+1.0x ao multiplicador de dano crítico por nível', effectType: 'crit_mult', effectVal: 1.0 },
    { id: 'tree_combo_bonus', name: 'Ecos da Destruição', maxLevel: 5, costBase: 1200, costMult: 2.0, icon: '🔥', desc: '+25% de bônus adicional em todos os patamares de combo', effectType: 'combo_mult', effectVal: 0.25 },
    { id: 'tree_combo_time', name: 'Concentração Absoluta', maxLevel: 5, costBase: 1500, costMult: 2.2, icon: '⏳', desc: '+1 segundo de retenção antes de perder o combo', effectType: 'combo_time', effectVal: 1000 },
  ],

  // Conquistas com Recompensas
  ACHIEVEMENTS: [
    { id: 'first_win', name: 'Primeiro Passo Sombrio', desc: 'Complete a Onda 1 com sucesso.', icon: '🛡️', rewardCoins: 100, rewardXp: 50, reqType: 'wave', reqVal: 1 },
    { id: 'wave_10', name: 'Sobrevivente Noturno', desc: 'Alcance e vença a Onda 10.', icon: '⚔️', rewardCoins: 500, rewardXp: 200, reqType: 'wave', reqVal: 10 },
    { id: 'wave_25', name: 'Defensor Implacável', desc: 'Supere a terrível Onda 25.', icon: '🏰', rewardCoins: 1500, rewardXp: 600, reqType: 'wave', reqVal: 25 },
    { id: 'wave_50', name: 'Lenda das Trevas', desc: 'Resista até a lendária Onda 50.', icon: '🌟', rewardCoins: 8000, rewardXp: 3000, reqType: 'wave', reqVal: 50 },
    { id: 'first_boss', name: 'Regicida Sombrio', desc: 'Derrote o primeiro Chefe (Rei Zumbi).', icon: '👑', rewardCoins: 800, rewardXp: 300, reqType: 'bosses', reqVal: 1 },
    { id: 'ten_bosses', name: 'Cacador de Pesadelos', desc: 'Destrua 10 Chefes temíveis.', icon: '💀', rewardCoins: 5000, rewardXp: 2000, reqType: 'bosses', reqVal: 10 },
    { id: 'clicks_100', name: 'Dedos Rápidos', desc: 'Execute 100 cliques no Cristal Sombrio.', icon: '👆', rewardCoins: 200, rewardXp: 100, reqType: 'clicks', reqVal: 100 },
    { id: 'clicks_1000', name: 'Obsessão pelo Cristal', desc: 'Alcance 1.000 cliques no total.', icon: '💎', rewardCoins: 1500, rewardXp: 500, reqType: 'clicks', reqVal: 1000 },
    { id: 'combo_100', name: 'Frenesi Cósmico', desc: 'Atinja uma sequência de 100 cliques sem parar.', icon: '🔥', rewardCoins: 1000, rewardXp: 400, reqType: 'max_combo', reqVal: 100 },
    { id: 'combo_500', name: 'Possessão Sombria', desc: 'Atinja a lendária sequência de 500 cliques.', icon: '⚡', rewardCoins: 5000, rewardXp: 2500, reqType: 'max_combo', reqVal: 500 },
    { id: 'coins_10k', name: 'Tesoureiro das Trevas', desc: 'Acumule 10.000 moedas no total.', icon: '💰', rewardCoins: 2000, rewardXp: 800, reqType: 'total_coins', reqVal: 10000 },
    { id: 'coins_100k', name: 'Magnata do Vazio', desc: 'Acumule 100.000 moedas no total.', icon: '🪙', rewardCoins: 10000, rewardXp: 4000, reqType: 'total_coins', reqVal: 100000 },
    { id: 'mythic_tower', name: 'Poder Supremo', desc: 'Construa ou evolua uma torre para o nível Mítico.', icon: '🌌', rewardCoins: 6000, rewardXp: 3000, reqType: 'has_mythic', reqVal: 1 },
    { id: 'kills_500', name: 'Purificador da Noite', desc: 'Extermine 500 criaturas sombrias.', icon: '🩸', rewardCoins: 2500, rewardXp: 1200, reqType: 'kills', reqVal: 500 },
  ],

  // Recompensas de Onda
  getWaveReward: function(wave) {
    if (wave === 1) return 50;
    if (wave === 5) return 150;
    if (wave === 10) return 300;
    if (wave === 20) return 700;
    if (wave === 50) return 3000;
    // Fórmula progressiva para outras ondas
    return Math.floor(40 + wave * 22 + Math.pow(wave, 1.45) * 4);
  }
};
